Documentation update
CMSgov/hpt-validator pull request #47
Opened 2024-07-11 20:21 UTC by shaselton-usds

Node version documentation for the test suite.

2024-07-12 02:54 UTC, eoverly commented
Perfect, thanks!

2024-07-12 02:56 UTC, eoverly approved these changes
Looks Good!

2024-07-12 16:00 UTC, mint-thompson requested changes

2024-07-12 16:00 UTC, mint-thompson commented on README.md
> +If you are running the following command, it has been observed that Node versions 20+ encounter typescript errors. The test suite will run using Node version 19.*.*.
This is talking about the command on line 22, right? So I think it would be the "previous" command, not the "following" command.

2024-07-16 13:56 UTC, mint-thompson approved these changes

2024-07-16 18:47 UTC, merged