Validate using 2.0 CSV tall format and 2.0 JSON format
CMSgov/hpt-validator pull request #7
Opened 2024-01-25 21:34 UTC by mint-thompson

This PR adds functionality and tests for validating columns and rows using the 2.0 CSV tall format. This PR does _not_ include validation checks that are considered to be "conditional checks". There are some new small utility methods for validating enumerated and numeric fields. These functions should be useful when implementing the 2.0 CSV wide format.

Also included in this PR are functionality and tests for the 2.0 JSON format, since that PR was merged targeting the `tall-format-2.0` branch.

2024-01-29 21:45 UTC, shaselton-usds commented on test/2.0/csv.spec.ts
> +    "code | 2 | type": "",
@mint-thompson Just to confirm (and I don't want this to hold up this PR), but if you have a "code | 3" _without_ a corresponding "code | 3 | type", the validator would not flag that, correct?

I tired adding a "code | 3" without the corresponding "type" header and reran the tests and they all passed. Just want to confirm current expected behavior.

2024-01-31 00:32 UTC, shaselton-usds commented on src/csv.ts
>  import { CsvValidatorOneOne } from "./versions/1.1/csv.js"
Pretty sure we are going to want to import the new version here.

2024-01-31 00:34 UTC, shaselton-usds requested changes
Importing the new version to be used is going to be needed.

2024-01-31 15:00 UTC, shaselton-usds approved these changes

2024-01-31 17:08 UTC, carrils approved these changes

2024-01-31 17:55 UTC, merged